version: '2' 
services:
    web:
        image: dockercloud/hello-world
    lb:
        image: dockercloud/haproxy
        ports:
            - 80:80
            - 1936:1936
        links:
            - web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
