version: '2'
services:
    lb:
        build:
             context: .
             image: eeacms/haproxy
        ports:
            - "80:80"
            - "1936:1936"
        links:
            - web
			

    web:
        build:
            context: .
            dockerfile: web-dockerfile
        ports:
            - "80"
